apiVersion: apps/v1
kind: Deployment
metadata:
  name: testwf
  labels:
    app: testwf
  namespace: namespace-workflow-1692021132726
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testwf
  template:
    metadata:
      labels:
        app: testwf
    spec:
      containers:
        - name: testwf
          image: myrepository2023.azurecr.io/image-workflow-1692021132726:latest
          ports:
            - containerPort: 3000