apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd
  labels:
    app: cd
  namespace: namespace-workflow-1692025912099
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cd
  template:
    metadata:
      labels:
        app: cd
    spec:
      containers:
        - name: cd
          image: myrepository2023.azurecr.io/image-workflow-1692025912099:latest
          ports:
            - containerPort: 3000