apiVersion: v1
kind: Service
metadata:
  name: testwf
  namespace: namespace-workflow-1692021132726
spec:
  type: LoadBalancer
  selector:
    app: testwf
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000