apiVersion: v1
kind: Service
metadata:
  name: CD
  namespace: namespace-workflow-1692025496646
spec:
  type: LoadBalancer
  selector:
    app: CD
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000