apiVersion: v1
kind: Service
metadata:
  name: cd
  namespace: namespace-workflow-1692025912099
spec:
  type: LoadBalancer
  selector:
    app: cd
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000